### ISSUE TITLE
Newly added chains are not showing up

### ISSUE THREAD

**Issue by aqeelVaival** [DefiLlama/defillama-sdk#120]
I added two chains here via PR
https://github.com/DefiLlama/chainlist/pull/746
& it has been merged as well. i want to get start on an adapter but [here](https://github.com/DefiLlama/defillama-sdk/blob/master/src/providers.json) i am unable to see recently added chains (1338,1339). Please let me know on it , thanks

**Comment by g1nt0ki** [comment]
https://unpkg.com/@defillama/sdk@latest/build/providers.json I can see them here
