### ISSUE TITLE
add multicall v3 support

### ISSUE THREAD

**Issue by 007vasy** [DefiLlama/defillama-sdk#80]
https://github.com/mds1/multicall

there is a new multicall version (v3) which is deployed over 50+ networks with the same address:
[https://github.com/mds1/multicall#multicall3-contract-addresses](https://github.com/mds1/multicall#multicall3-contract-addresses)

**Comment by Pasko121** [comment]
> https://github.com/mds1/multicall
> 
> 
> 
> there is a new multicall version (v3) which is deployed over 50+ networks with the same address:
> 
> [https://github.com/mds1/multicall#multicall3-contract-addresses](https://github.com/mds1/multicall#multicall3-contract-addresses)

Thanks!****

**Comment by g1nt0ki** [comment]
@007vasy responding bit late, but we have multicall3 support now https://github.com/DefiLlama/defillama-sdk/blob/master/src/abi/multicall3.ts

**Comment by 007vasy** [comment]
@g1nt0ki cool :D good job :)
